name: armTemplateDeployment

on:
   workflow_dispatch:
jobs:

  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/Login@v1
        with:
          creds:${{secrets.AZURE_CRDENTIALS}}
