name: armTemplateDeploy

on:
 
  workflow_dispatch:
jobs:
  armdeploy:
    runs-on: ubuntu-latest

     steps:
            - uses: actions/checkout@v1

            - name: Azure Login
              uses: Azure/Login@v1
              with:
                creds:${{secret.AZURE_CRDENTIALS}}
